### ISSUE TITLE
Host networking is not supported

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#12] opened 2017-01-30 16:37 UTC
_From @sameo on January 24, 2017 15:44_

We do not support running Clear Containers within the host network (`docker --net=host run foo`).
Although this sounds like a corner case, it seems that Kubernetes starts at least one such container per node (for kube-proxy) in order to mess with the host iptables and routes.

_Copied from original issue: 01org/cc-oci-runtime#617_

**Comment by dlespiau** [comment] 2017-05-25 17:51
@sameo now that CRI-O knows about privileged containers we can close this one right?

**Comment by mcastelino** [comment] 2017-07-18 16:39
@dlespiau Just to clarify, we do not support host networking with clear containers. With CRI-O we have the option of running containers that need host networking to opt for a different runtime like runc.

**Comment by egernst** [comment] 2017-07-18 16:48
While the name of the issue is accurate, I think this is "resolved but will not be fixed."  

Closing this -- feel free to reopen if I am mistaken.

**Closed by egernst** 2017-07-18 16:48 UTC
Labels: domain:networking, P1

**Comment by jodh-intel** [comment] 2017-07-18 16:54
I wonder if we should add a "Limitations" section to the top-level README to document this to avoid users having to trawl around to find a closed issue? @grahamwhaley - what are your thoughts on this?

**Comment by mcastelino** [comment] 2017-07-18 16:58
@jodh-intel @grahamwhaley We should. There are other limitations which we need to document

Lack of current support for
- network connect 
- --device
- -v when used with devices
- --shm-size

**Comment by grahamwhaley** [comment] 2017-07-18 17:04
+1
I definitely think we should. I've run into the host network one myself, and would like to know what the others are.
Some technical background on the why, any known alternatives or workarounds, and any roadmap plans of how to fix them etc. would also be welcomed ;-)

**Comment by egernst** [comment] 2017-07-18 17:20
@grahamwhaley @mcastelino @jodh-intel : see https://github.com/clearcontainers/runtime/issues/338 for tracking this limitation update.
