### ISSUE TITLE
docker swarm leaving replicas in created mode

### ISSUE THREAD

**Issue by GabyCT** [clearcontainers/runtime#443] opened 2017-08-21 19:41 UTC
With the following configuration:
Fedora 25
Docker 17.06.1-ce
cc-runtime 3.0.0-beta.1
commit   : 48255158a15166ecaae2497c3b15f203b7728727
OCI specs: 1.0.0-rc5

While starting swarm and then creating a service to launch swarm replicas, it is seen that replicas are 
shown in "created" mode or not running
CONTAINER ID        IMAGE                 COMMAND                   CREATED             STATUS                        PORTS               NAMES
1686ced00a9c        gabyct/nginx:latest   "sh -c '\"hostname ..."   2 seconds ago       Created                                           test.1.wc9cruvrx3aj7n7i3v80n2mli
51e8ee70c83c        gabyct/nginx:latest   "sh -c '\"hostname ..."   9 seconds ago       Exited (127) 2 seconds ago                        test.1.nhmnrsb27hoi1uxl2fkyvzy3l
e849382dd470        gabyct/nginx:latest   "sh -c '\"hostname ..."   16 seconds ago      Exited (127) 9 seconds ago                        test.1.lnhlknuss20lwa668v1jgimkw
8eda4543e783        gabyct/nginx:latest   "sh -c '\"hostname ..."   22 seconds ago      Exited (127) 16 seconds ago                       test.1.6k8qe8b2dnwca6hbvts9r4jon
0205ee1fc74c        gabyct/nginx:latest   "sh -c '\"hostname ..."   29 seconds ago      Exited (127) 23 seconds ago                       test.1.bj5pw2888pn8p1xt62h0qryu7
95ded7a418ba        gabyct/nginx:latest   "sh -c '\"hostname ..."   37 seconds ago      Exited (127) 30 seconds ago                       test.1.dzm4ls7haix860hm5kplx0ck1

**Comment by amshinde** [comment] 2017-09-14 20:00
Tried reproducing this in a Fedora VM with ciao-down, was not able to do so. I see that the containers are in running state and can be exec'ed into.
```
$ sudo docker swarm init
Swarm initialized: current node (j19wxzqbx16wv3617fllqohsq) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join --token SWMTKN-1-5u3ao2g6axixn9o2978jlfr644keqxutnk6wf2k113ah3c8ivy-2lsqxlzmhq9ys5zhchqqjw1yu 10.0.2.15:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.

[amshinde@singlevm ~]$ sudo docker service create --name testswarm --replicas 4 --publish 8080:80 nginx /bin/bash -c "hostname > /usr/share/nginx/html/hostname; nginx -g \"daemon off;\""
ljzuvrv2fcku2xp9pv6esshu4
Since --detach=false was not specified, tasks will be created in the background.
In a future release, --detach=false will become the default.

$ sudo docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
3b54b9ebae5b        nginx:latest        "/bin/bash -c 'hos..."   14 seconds ago      Up 8 seconds        80/tcp              testswarm.1.px7685r2n3yynd324vguryurz
f97c7c24e0bb        nginx:latest        "/bin/bash -c 'hos..."   15 seconds ago      Up 9 seconds        80/tcp              testswarm.3.pofjifwhrza3x54zjb4h5slgr
1f51b9cab398        nginx:latest        "/bin/bash -c 'hos..."   15 seconds ago      Up 8 seconds        80/tcp              testswarm.2.tr554n6c6lozazyp2c48dpqsf
2f5820f808a3        nginx:latest        "/bin/bash -c 'hos..."   15 seconds ago      Up 7 seconds        80/tcp              testswarm.4.kjuhulx7bcidrnojw84y5btz1

sudo docker service ps testswarm
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE           ERROR               PORTS
px7685r2n3yy        testswarm.1         nginx:latest        singlevm            Running             Running 5 minutes ago                       
tr554n6c6loz        testswarm.2         nginx:latest        singlevm            Running             Running 5 minutes ago                       
pofjifwhrza3        testswarm.3         nginx:latest        singlevm            Running             Running 5 minutes ago                       
kjuhulx7bcid        testswarm.4         nginx:latest        singlevm            Running             Running 5 minutes ago   
```

**Comment by amshinde** [comment] 2017-09-14 20:03
I have tried the above with 
Fedora 25
Docker 17.06.2-ce
cc-runtime  : 3.0.0-beta.2
commit   : d5a569a1cf65584380339414ed430c315376a036
OCI specs: 1.0.0-rc5

@egernst Not able to reproduce this issue, can we close this?

**Closed** 2017-09-14 20:05 UTC
Labels: bug, release gating
