### ISSUE TITLE
container can not be killed or deleted after running in detach mode

### ISSUE THREAD

**Issue by GabyCT** [clearcontainers/runtime#343] opened 2017-07-19 18:41 UTC
It is not possible to delete or kill a container after running in standalone in detach mode

1. cc-runtime run -d --bundle /home/cloud/rootfs/ testtwo

2. cc-runtime state testtwo
{"ociVersion":"1.0.0-rc5","id":"testtwo","status":"running","pid":21904,"bundle":"/home/cloud/rootfs","annotations":{"com.github.containers.virtcontainers.pkg.oci.bundle_path":"/home/cloud/rootfs","com.github.containers.virtcontainers.pkg.oci.config_path":"/home/cloud/rootfs/config.json","com.github.containers.virtcontainers.pkg.oci.container_type":"pod_sandbox"}}

3. cc-runtime kill testtwo

4. cc-runtime state testtwo
{"ociVersion":"1.0.0-rc5","id":"testtwo","status":"running","pid":21904,"bundle":"/home/cloud/rootfs","annotations":{"com.github.containers.virtcontainers.pkg.oci.bundle_path":"/home/cloud/rootfs","com.github.containers.virtcontainers.pkg.oci.config_path":"/home/cloud/rootfs/config.json","com.github.containers.virtcontainers.pkg.oci.container_type":"pod_sandbox"}}

5. cc-runtime delete testtwo --force
Could not get veth interface: LinkByName() failed for veth name eth0: Link not found

**Comment by GabyCT** [comment] 2017-07-19 18:42
This is the setup
cc-runtime : 3.0.0-alpha.3
OCI specs: 1.0.0-rc5

On ubuntu 16.10

**Comment by egernst** [comment] 2017-08-22 21:59
Log of proxy when recreating this failure to kill:
https://paste.fedoraproject.org/paste/Y3wOKYgRU8Ls9uMJLzkeew

**Comment by egernst** [comment] 2017-08-22 22:00
@sboeuf - have you tested running in detached mode?

**Comment by sboeuf** [comment] 2017-08-22 23:47
I don't think so. I'll take a look later

**Comment by amshinde** [comment] 2017-08-22 23:58
Tried this out with the latest binaries, looks like the signal is propagated to the container with 
cc-runtime kill. The signal sent is Signal 15 or SIGTERM.

But the state still shows the container running. 
The delete command does not give me any errors. I see the same logs as @egernst.
Logs show that the container was successfully deleted.

I tried this out with explicitly sending a signal 9 as:
cc-runtime kill test 9.
The container process is terminated in this case and the state is changed to stopped. So the issue seems to be with SIGTERM signal.

**Comment by sboeuf** [comment] 2017-08-23 00:12
@amshinde what is the workload running for this container ? And have we compared this with runc ?
SIGTERM behaves in a weird way with runc/libcontainer.

**Comment by amshinde** [comment] 2017-08-23 00:20
@sboeuf I have tested this with a busybox rootfs running "sh". Will try out with runc next.

**Comment by amshinde** [comment] 2017-08-23 00:57
@GabyCT What is the workload and rootfs image that you used for the test?

**Comment by amshinde** [comment] 2017-08-23 01:22
I tested the same busybox rootfs running "sh" with runc:
```
sudo runc run -d --bundle ~/busybox --console-socket=/tmp/console.sock  test2
```

With 
```
sudo runc kill test2 SIGTERM
```
I still see the container as running.
The container is stopped only with sudo runc kill test2 SIGKILL.
Seen the same behaviour in attached case.

So, Clear Containers behaviour is same as runc.

**Comment by sboeuf** [comment] 2017-08-23 08:30
@GabyCT please retry your testing with `runc` and tell us if you get the same behavior than @amshinde.
In case you get the same result, I think we can consider closing this issue.

**Comment by egernst** [comment] 2017-08-30 11:54
Based on @amshinde comment regarding being the same as runc, this issue should be closed as not a bug.

**Closed** 2017-08-30 11:54 UTC
Labels: bug, CC 3.0, release gating
