### ISSUE TITLE
Update the architecture document

### ISSUE THREAD

**Issue by sameo** [clearcontainers/runtime#104] opened 2017-05-03 13:00 UTC
Update the [current document](https://github.com/01org/cc-oci-runtime/blob/master/documentation/architecture.md) to follow the 3.0 architectural changes

**Comment by grahamwhaley** [comment] 2017-08-14 15:40
Also see #392

**Comment by egernst** [comment] 2017-09-12 18:39
duplicate of  #392

**Closed by egernst** 2017-09-12 18:39 UTC
Labels: domain:documentation
